### ISSUE TITLE
Could not build opendis6 library as shared

### ISSUE THREAD

**Issue by uilianries** [crhowell3/opendis6#4]
### What version of Open DIS C++ is running?

0.1.0

### What platform is your computer?

Darwin 23.3.0 arm64 arm

### What steps can reproduce the bug?

```
$ wget https://github.com/crhowell3/opendis6/archive/refs/tags/0.1.0.tar.gz
$ tar zxf 0.1.0.tar.gz
$ cd opendis6-0.1.0
$ cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
$ cmake --build build
```

### What is the expected behavior?

I would expect building it as shared library. It works fine when building as static library.

### What do you see instead?

Github does not allow my log here because it passes the size limit. I copied it to a public gist instead: https://gist.github.com/uilianries/2f96dbaef771a8c3d09b1b5d609415fd

### Additional information

I'm using Mac M1 with Clang 15:

```
clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by crhowell3** [comment]
I am investigating this issue now. I am having some trouble replicating this. The shared libraries build fine with GCC (8.5.0+), and I am using `clang version 16.0.6 (Red Hat 16.0.6-2.module_el8.9.0+3621+df7f7146)` with no issue. This could very well be an issue with the Apple Clang compiler, which I am unable to test at this point in time. Any suggestions with that? I may not be able to support MacOS with this library

**Comment by uilianries** [comment]
> Any suggestions with that? I may not be able to support MacOS with this library

Let me build and check here. One thing that you could do is adding a Github actions to build your library, so you could always validate in Linux, Mac and Windows for free.

**Comment by uilianries** [comment]
@crhowell3 An extra build log: https://github.com/conan-io/conan-center-index/pull/22646#issuecomment-1930311584

The CI used Linux Ubuntu to build that configuration. You can see the full log in a link, in the same comment. 

In case you have Docker, you can try:

```
docker run --rm -ti --platform=linux/amd64 conanio/gcc7
# In the container
$ wget https://github.com/crhowell3/opendis6/archive/refs/tags/0.1.0.tar.gz
$ tar zxf 0.1.0.tar.gz
$ cd opendis6-0.1.0
$ cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
$ cmake --build build
```

The second image was with GCC 11, the docker image is `conanio/gcc11-ubuntu16.04:2.0.17`

**Comment by crhowell3** [comment]
I figured out the problem! Will push changes shortly and re-release 0.1.0. This should fix the linking issues.

**Comment by uilianries** [comment]
Amazing! Thank you!
